# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.school }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
school: Houston Coding Academy
key: houston
header: Houston's Best Value in Coding Education
email: info@houstontxcodingacademy.com
baseurl: "" # the subpath of your site, e.g. /blog
url: https://houstontxcodingacademy.com # the base hostname & protocol for your site, e.g. http://example.com
twitter: https://twitter.com/AustinCoding
github:  https://github.com/AustinCodingAcademy
facebook: https://www.facebook.com/AustinCodingAcademy
instagram: https://www.instagram.com/austincodingacademy
googleplus: https://plus.google.com/+AustinCodingAcademy
linkedin: https://www.linkedin.com/company/austin-coding-academy
google:
yelp:
coursereport:
switchup:
thinkful:
phone: (832) 779-2108
location: 'Station Houston, 1301 Fannin St #2440, Houston, TX 77002'
location_url: https://goo.gl/maps/3LrV6umVPc32
city: Houston
paginate: 5
next_session: April 10th, 2017
course_amount: $3,490
track_amount: $10,470
stack: csharp
google_tag_id: GTM-NWVBXXW
syllabus: https://student.austincodingacademy.com/_book/houston-intro.html
color: '#f0492e'

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - vendor
  - README.md
  - circle.yml
  - faviconData.json
