# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.school }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
school: Dallas Coding Academy
header: Dallas' Best Value in Coding Education
email: info@dallascodingacademy.com
baseurl: "" # the subpath of your site, e.g. /blog
url: https://dallascodingacademy.com # the base hostname & protocol for your site, e.g. http://example.com
twitter: https://twitter.com/AustinCoding
github:  https://github.com/AustinCodingAcademy
facebook: https://www.facebook.com/AustinCodingAcademy
instagram: https://www.instagram.com/austincodingacademy
googleplus: https://plus.google.com/+AustinCodingAcademy
linkedin: https://www.linkedin.com/company/austin-coding-academy
google:
yelp:
coursereport:
switchup:
thinkful:
phone: (469) 340-1194
location: '17290 Preston Rd #300, Dallas, TX 75252'
location_url: https://goo.gl/maps/KYNdbWyKZnD2
city: Dallas
paginate: 5
next_session: January 24th, 2017
course_amount: $3,490
track_amount: $10,470
stack: csharp
google_tag_id: GTM-NGPHTVR
syllabus: https://student.austincodingacademy.com/_book/dallas-intro.html

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - vendor
  - README.md
