# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.school }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
school: San Antonio Coding Academy
acronym: SACA
key: sanantonio
email: info@sanantoniocodingacademy.com
header: San Antonio's Best Value in Coding Education
baseurl: "" # the subpath of your site, e.g. /blog
url: https://sanantoniocodingacademy.com # the base hostname & protocol for your site, e.g. http://example.com
twitterhandle: SACodingAcademy
twitter: https://twitter.com/SACodingAcademy
github:  https://github.com/AustinCodingAcademy
facebook: https://www.facebook.com/SanAntonioCodingAcademy/
instagram: https://www.instagram.com/sanantoniocodingacademy/
googleplus: https://plus.google.com/114897680856172944100
linkedin: https://www.linkedin.com/company/austin-coding-academy
google:
yelp:
coursereport:
switchup:
thinkful:
phone: (210) 951-0407
location: Launch SA, 600 Soledad St, San Antonio, TX 78205
location_url: https://goo.gl/maps/So4e2w6Y6BB2
city: San Antonio
course_amount: $2,990
track_amount: $8,970
stack: csharp
google_tag_id: GTM-KPK9R39
google_analytics: UA-89726336-1
pixel_id: 656599271106549
syllabus: https://student.austincodingacademy.com/sanantonio-intro.html
color: '#82ca9c'
map: https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d13899.14382366836!2d-98.4946427!3d29.4350517!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x865c5f51a21d2429%3A0x89f4c49b30b4ca34!2sSan+Antonio+Coding+Academy!5e0!3m2!1sen!2sus!4v1488738159410
eventbrite_organizer_id: 12423084089
eventbrite: https://www.eventbrite.com/o/san-antonio-coding-academy-12423084089
courses:
  - 101
  - 221
  - 321
tracks:
  - CSharp
classtimes: 6:15pm - 8:45pm
# Build settings
announcement: Classes begin <span class="start-date-only"></span>!
markdown: kramdown
permalink: blog/:year/:month/:day/:slug/

gems:
  - jekyll-feed
  - jekyll-redirect-from
  - amp-jekyll
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - vendor
  - README.md
  - circle.yml
  - faviconData.json
  - npm-debug.log
