# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.school }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
school: Dallas Coding Academy
acronym: DCA
key: dallas
header: Dallas' Best Value in Coding Education
email: info@dallascodingacademy.com
baseurl: "" # the subpath of your site, e.g. /blog
url: https://dallascodingacademy.com # the base hostname & protocol for your site, e.g. http://example.com
twitter: https://twitter.com/DallasCoding
github:  https://github.com/AustinCodingAcademy
facebook: https://www.facebook.com/Dallas-Coding-Academy-282557825471877/
instagram: https://www.instagram.com/austincodingacademy
googleplus: https://plus.google.com/104603863969297208216
linkedin: https://www.linkedin.com/company/austin-coding-academy
google:
yelp:
coursereport:
switchup:
thinkful:
phone: (469) 340-1194
location: 'NoD, 17290 Preston Rd #300, Dallas, TX 75252'
location_url: https://goo.gl/maps/KYNdbWyKZnD2
city: Dallas
paginate: 5
next_session: April 24th, 2017
course_amount: $3,490
track_amount: $10,470
stack: csharp
google_tag_id: GTM-NGPHTVR
syllabus: https://student.austincodingacademy.com/dallas-intro.html
color: '#00b7d4'
map: https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d53547.08669260216!2d-96.8145675769043!3d32.98550266608447!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x864c23d82a355e97%3A0x648717743f3c2312!2sDallas+Coding+Academy!5e0!3m2!1sen!2sus!4v1488737990435
eventbrite_organizer_id: 12701002998
eventbrite: https://www.eventbrite.com/o/dallas-coding-academy-12701002998
courses:
  - 101
  - 221
  - 321

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - vendor
  - README.md
  - circle.yml
  - faviconData.json
