twitter: https://twitter.com/AustinCoding
github:  https://github.com/AustinCodingAcademy
facebook: https://www.facebook.com/AustinCodingAcademy
instagram: https://www.instagram.com/austincodingacademy
googleplus: https://plus.google.com/+AustinCodingAcademy
linkedin: https://www.linkedin.com/company/austin-coding-academy
google:
yelp:
coursereport:
switchup:
thinkful:
google_tag_id: GTM-KXWTBGW
pixel_id: 656599271106549
classtimes: 6:30pm - 9:00pm
tracks:
announcement:
phone: (512) 827-8498

# Build settings
markdown: kramdown
permalink: :year/:month/:day/:slug/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - vendor
  - README.md
  - faviconData.json
  - npm-debug.log
  - package-lock.json
  - yarn.lock
  - deploy.js
  - dns.js
  - yarn-error.log

plugins:
  - liquid-md5
