key: austin
acronym: ACA
city: Austin
color: '#F5B02C'
lighter_color: '#fce0ad'
phone: (512) 827-8498
locations:
  - address: Capital Factory,<br>701 Brazos St, Ste 1616,<br>Austin, TX 78701
    url: https://goo.gl/maps/Kgtw4DtyH4n
  - address: Austin Coding Academy,<br>314 E Highland Mall Blvd, Ste 114,<br>Austin, TX 78752
    url: https://www.google.com/maps/place/314+E+Highland+Mall+Blvd+%23114,+Austin,+TX+78752/@30.3290995,-97.7136125,17z/data=!4m13!1m7!3m6!1s0x8644ca3c817930a1:0xf2f7e3c8049a68fe!2s314+E+Highland+Mall+Blvd+%23114,+Austin,+TX+78752!3b1!8m2!3d30.3290949!4d-97.7114185!3m4!1s0x8644ca3c817930a1:0xf2f7e3c8049a68fe!8m2!3d30.3290949!4d-97.7114185
map: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3445.884375397476!2d-97.74275278487958!3d30.2688754818011!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8644b4e31ad087bd%3A0xd6644ce54fe2531c!2sAustin+Coding+Academy!5e0!3m2!1sen!2sus!4v1488689585071
eventbrite_organizer_id: 10937668459
eventbrite: https://www.eventbrite.com/o/austin-coding-academy-10937668459
start_date: Mon, Jan 14th, 2019
announcement: Classes Begin Mon, Jan 14th!
course_amount: $2,990
track_amount: $8,970
tracks:
  - javascript
  - csharp
  - webdesign
twitter: https://twitter.com/AustinCoding
github:  https://github.com/AustinCodingAcademy
facebook: https://www.facebook.com/AustinCodingAcademy
instagram: https://www.instagram.com/austincodingacademy
googleplus: https://plus.google.com/+AustinCodingAcademy
linkedin: https://www.linkedin.com/company/austin-coding-academy
length: '10 Weeks'