twitterhandle: AustinCoding
twitter: https://twitter.com/AustinCoding
github:  https://github.com/AustinCodingAcademy
facebook: https://www.facebook.com/AustinCodingAcademy
instagram: https://www.instagram.com/austincodingacademy
googleplus: https://plus.google.com/+AustinCodingAcademy
linkedin: https://www.linkedin.com/company/austin-coding-academy
google:
yelp:
coursereport:
switchup:
thinkful:
course_amount: $2,990
track_amount: $8,970
google_tag_id: GTM-TBH7GK
pixel_id: 656599271106549
classtimes: 6:30pm - 9:00pm
courses:
  - 101
  - 221
  - 321
announcement: Classes begin <span class="start-date-only"></span>!
phone: (512) 827-8498
color: '#f8b232'
css: austin
logo: austin
# Build settings
markdown: kramdown
permalink: :year/:month/:day/:slug/

gems:
  - jekyll-feed
  - jekyll-redirect-from
  # - amp-jekyll
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - vendor
  - README.md
  - faviconData.json
  - npm-debug.log
