city: Lubbock
key: lubbock
acronym: LCA
color: '#00b3d1'
lighter_color: '#00b3d1'
start_date: February 4th
phone: (806) 905-5021
locations:
 - address: South Plain College Lubbock Center,<br>3907 Avenue Q, Lubbock,<br>TX 79412
   url: https://www.google.com/maps/place/South+Plains+College+Lubbock+Center/@33.5577634,-101.8559531,17z/data=!3m1!4b1!4m5!3m4!1s0x86fe6d1839084583:0x8bdaa2a3477f2bc8!8m2!3d33.5577634!4d-101.8537644
announcement: Classes Begin on February 4th!
track_amount: $5,960
tracks:
subheader: In Partnership with South Plains College
classtimes: 6:00pm - 9:00pm
facebook: https://www.facebook.com/LubbockCodingAcademy/
instagram: https://www.instagram.com/lubbockcodingacademy/
weeks: 8
assignment_form_id: '12a277a2-d645-48b6-9e9a-11aa43e33da4'
application_form_id: '3abd444f-ac31-4c9c-8448-c7f4c25eb9d7'
schedule_qa_url: https://acaappointment.as.me/?appointmentType=8404564
pixel_id: 1998494793577339
